initial
Traceback (most recent call last):
  File "/scrtp/avon/eb/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages/fsspec/registry.py", line 226, in get_filesystem_class
    register_implementation(protocol, _import_class(bit["class"]))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scrtp/avon/eb/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages/fsspec/registry.py", line 249, in _import_class
    mod = importlib.import_module(mod)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scrtp/avon/eb/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'gcsfs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/home/stats/stubxk/Probabilistic_Scorecard/ProbScoreCard.py", line 35, in <module>
    observationsera = xr.open_zarr(obs_path)
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stats/stubxk/newenv4/lib/python3.11/site-packages/xarray/backends/zarr.py", line 867, in open_zarr
    ds = open_dataset(
         ^^^^^^^^^^^^^
  File "/home/stats/stubxk/newenv4/lib/python3.11/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/stats/stubxk/newenv4/lib/python3.11/site-packages/xarray/backends/zarr.py", line 934, in open_dataset
    store = ZarrStore.open_group(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/stats/stubxk/newenv4/lib/python3.11/site-packages/xarray/backends/zarr.py", line 427, in open_group
    zarr_group = zarr.open_consolidated(store, **open_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stats/stubxk/newenv4/lib/python3.11/site-packages/zarr/convenience.py", line 1343, in open_consolidated
    store = normalize_store_arg(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/stats/stubxk/newenv4/lib/python3.11/site-packages/zarr/storage.py", line 201, in normalize_store_arg
    return normalize_store(store, storage_options, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stats/stubxk/newenv4/lib/python3.11/site-packages/zarr/storage.py", line 171, in _normalize_store_arg_v2
    return FSStore(store, mode=mode, **(storage_options or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stats/stubxk/newenv4/lib/python3.11/site-packages/zarr/storage.py", line 1384, in __init__
    self.map = fsspec.get_mapper(url, **{**mapper_options, **storage_options})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scrtp/avon/eb/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages/fsspec/mapping.py", line 237, in get_mapper
    fs, urlpath = url_to_fs(url, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scrtp/avon/eb/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages/fsspec/core.py", line 363, in url_to_fs
    chain = _un_chain(url, kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/scrtp/avon/eb/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages/fsspec/core.py", line 325, in _un_chain
    cls = get_filesystem_class(protocol)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scrtp/avon/eb/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages/fsspec/registry.py", line 228, in get_filesystem_class
    raise ImportError(bit["err"]) from e
ImportError: Please install gcsfs to access Google Storage
srun: error: node061: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=1515577.0
